import type { KnowledgeItem } from './knowledge.types';

/**
 * KNOWLEDGE CONTENT SEED — Phase 2.
 *
 * Real Arabic-first seed content covering every public category plus an
 * internal-operations section. Every item is grounded in the actual
 * platform behaviour — no invented features, no fake numbers.
 *
 * Conventions:
 *  - Arabic body is mandatory for published items.
 *  - `usableByAssistant` is true ONLY for items safe to surface as a
 *    knowledge answer (no message-only copy, no internal-only notes).
 *  - `usableInMessages` is true ONLY for short customer/provider-safe
 *    snippets meant for transactional templates.
 *  - `categoryId` MUST match a slug from `knowledgeCategories.ts`.
 */

const ITEMS: KnowledgeItem[] = [
  // ============================== GENERAL ==============================
  {
    id: 'gen-what-is-qitaat',
    type: 'faq',
    categoryId: 'general',
    title: { ar: 'ما هي قطاعات؟', en: 'What is Qitaat?' },
    summary: { ar: 'منصة سعودية تربط العملاء بمزودي خدمات الصناعات الخفيفة (ألمنيوم، زجاج، خشب، حديد، وغيرها).' },
    body: { ar: 'قطاعات منصة سعودية تساعد العملاء والمنشآت على الوصول إلى مزودي خدمات الصناعات الخفيفة وإدارة طلبات عروض الأسعار والمتابعة من مكان واحد.' },
    audience: ['visitor','customer','provider','business_owner'],
    tags: ['platform','faq','general'],
    source: 'knowledge-seed-phase-2',
    status: 'published',
    priority: 100,
    relatedRoutes: ['/','/about'],
    usableByAssistant: true, usableInMessages: true,
  },
  {
    id: 'gen-who-can-use',
    type: 'faq', categoryId: 'general',
    title: { ar: 'من يمكنه استخدام قطاعات؟' },
    body: { ar: 'يمكن للأفراد، أصحاب المنشآت، المقاولين، والمزودين استخدام قطاعات. كل دور يحصل على لوحة تحكم مناسبة لاحتياجه.' },
    audience: ['visitor','customer','provider','business_owner'],
    tags: ['platform','faq'], source: 'knowledge-seed-phase-2', status: 'published', priority: 95,
    relatedRoutes: ['/','/for-providers'],
    usableByAssistant: true, usableInMessages: false,
  },
  {
    id: 'gen-how-platform-works',
    type: 'faq', categoryId: 'general',
    title: { ar: 'كيف تعمل المنصة؟' },
    body: { ar: 'تحدد احتياجك أو خدمتك، تنشئ حسابًا، ثم تستخدم لوحة التحكم لإرسال طلبات أو استقبالها ومتابعة الحالة حتى الانتهاء.' },
    audience: ['visitor','customer','provider'],
    tags: ['platform','getting-started','faq'], source: 'knowledge-seed-phase-2', status: 'published', priority: 92,
    relatedRoutes: ['/quote','/for-providers'], usableByAssistant: true, usableInMessages: false,
  },
  {
    id: 'gen-sectors-covered',
    type: 'faq', categoryId: 'general',
    title: { ar: 'ما القطاعات التي تغطيها قطاعات؟' },
    body: { ar: 'تشمل قطاعات الصناعات الخفيفة الأساسية مثل الألمنيوم، الزجاج، الخشب، الحديد، إضافة إلى خدمات تنفيذ وتركيب مرتبطة بها. يتم توسعة القطاعات تدريجيًا.' },
    audience: ['visitor','customer','provider'],
    tags: ['platform','faq'], source: 'knowledge-seed-phase-2', status: 'published', priority: 90,
    relatedRoutes: ['/categories'], usableByAssistant: true, usableInMessages: false,
  },
  {
    id: 'gen-how-to-start',
    type: 'guide', categoryId: 'general',
    title: { ar: 'كيف أبدأ في استخدام المنصة؟' },
    body: { ar: 'سجّل دخولك أو أنشئ حسابًا، ثم اختر نوع حسابك (عميل أو مزود)، وأكمل البيانات الأساسية. بعدها يمكنك إرسال طلب عرض سعر أو إنشاء ملف مزود.' },
    audience: ['visitor','customer','provider'],
    tags: ['onboarding','getting-started'], source: 'knowledge-seed-phase-2', status: 'published', priority: 88,
    relatedRoutes: ['/auth','/quote','/for-providers'], usableByAssistant: true, usableInMessages: true,
  },

  // ============================== CUSTOMERS ==============================
  {
    id: 'cust-how-to-request-quote',
    type: 'faq', categoryId: 'customers',
    title: { ar: 'كيف أطلب عرض سعر؟' },
    body: { ar: 'افتح صفحة "اطلب عرض سعر" واتبع الخطوات: اختر القطاع، أدخل تفاصيل المشروع، الموقع، والمدة، وأرفق الملفات عند الحاجة، ثم أرسل الطلب.' },
    audience: ['visitor','customer'],
    tags: ['rfq','quote','getting-started'], source: 'knowledge-seed-phase-2', status: 'published', priority: 95,
    relatedRoutes: ['/quote'], usableByAssistant: true, usableInMessages: true,
  },
  {
    id: 'cust-track-requests',
    type: 'faq', categoryId: 'customers',
    title: { ar: 'كيف أتابع طلباتي؟' },
    body: { ar: 'بعد تسجيل الدخول، افتح لوحة التحكم لعرض كل طلباتك مع حالتها (قيد المراجعة، تم الإرسال، استلم العروض، تم الإغلاق).' },
    audience: ['customer'],
    tags: ['rfq'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/dashboard/my-requests'], usableByAssistant: true, usableInMessages: true,
  },
  {
    id: 'cust-add-site',
    type: 'faq', categoryId: 'customers',
    title: { ar: 'كيف أضيف موقعًا؟' },
    body: { ar: 'من لوحة التحكم اختر "المواقع" ثم "إضافة موقع"، أدخل الاسم والمدينة والإحداثيات. يمكنك ربط الموقع لاحقًا بمشاريع أو طلبات.' },
    audience: ['customer','business_owner'],
    tags: ['sites'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/dashboard/sites'], usableByAssistant: true, usableInMessages: false,
  },
  {
    id: 'cust-add-project',
    type: 'faq', categoryId: 'customers',
    title: { ar: 'كيف أضيف مشروعًا؟' },
    body: { ar: 'من لوحة التحكم افتح "المشاريع" ثم "إضافة مشروع"، أكمل البيانات الأساسية واربط المشروع بموقع أو منشأة عند الحاجة.' },
    audience: ['customer','business_owner'],
    tags: ['projects'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/dashboard/projects'], usableByAssistant: true, usableInMessages: false,
  },
  {
    id: 'cust-use-without-business',
    type: 'faq', categoryId: 'customers',
    title: { ar: 'هل يمكنني استخدام قطاعات بدون منشأة؟' },
    body: { ar: 'نعم. الحساب الشخصي يكفي لإرسال طلبات عروض الأسعار وإدارة مشاريعك. إنشاء منشأة اختياري لمن يدير عمليات شركة.' },
    audience: ['visitor','customer'],
    tags: ['account'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/dashboard'], usableByAssistant: true, usableInMessages: false,
  },

  // ============================== BUSINESSES ==============================
  {
    id: 'biz-create-business',
    type: 'faq', categoryId: 'businesses',
    title: { ar: 'كيف أنشئ عمل/منشأة؟' },
    body: { ar: 'من لوحة التحكم افتح "المنشآت" ثم "إضافة منشأة"، أدخل البيانات التجارية الأساسية (الاسم، السجل، النشاط). يمكنك استكمال البيانات لاحقًا.' },
    audience: ['business_owner'],
    tags: ['business','onboarding'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/dashboard/businesses'], usableByAssistant: true, usableInMessages: false,
  },
  {
    id: 'biz-complete-data',
    type: 'faq', categoryId: 'businesses',
    title: { ar: 'كيف أستكمل بيانات العمل؟' },
    body: { ar: 'افتح ملف المنشأة وستجد شريط اكتمال البيانات يوضح الحقول المتبقية. كل ما زاد الاكتمال زادت ثقة العملاء وظهور المنشأة في النتائج.' },
    audience: ['business_owner'],
    tags: ['business'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/dashboard/businesses'], usableByAssistant: true, usableInMessages: false,
  },
  {
    id: 'biz-add-branches',
    type: 'faq', categoryId: 'businesses',
    title: { ar: 'كيف أضيف الفروع؟' },
    body: { ar: 'افتح المنشأة ثم "الفروع" واختر "إضافة فرع". لكل فرع اسم، مدينة، وبيانات تواصل، ويمكن ربطه بموقع جغرافي.' },
    audience: ['business_owner'],
    tags: ['business','branches'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/dashboard/businesses'], usableByAssistant: true, usableInMessages: false,
  },
  {
    id: 'biz-team-permissions',
    type: 'faq', categoryId: 'businesses',
    title: { ar: 'كيف أضيف فريق العمل والصلاحيات؟' },
    body: { ar: 'من إعدادات المنشأة اختر "الفريق" وأضف أعضاء بعناوين بريدية مع تحديد الدور (مالك، مدير، موظف). كل دور له صلاحيات محددة.' },
    audience: ['business_owner'],
    tags: ['business','team'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/dashboard/businesses'], usableByAssistant: true, usableInMessages: false,
  },
  {
    id: 'biz-when-public',
    type: 'faq', categoryId: 'businesses',
    title: { ar: 'متى تظهر الجهة للعامة؟' },
    body: { ar: 'تظهر المنشأة للعامة بعد استكمال البيانات الأساسية وتفعيل ملف الخدمات. بعض الميزات الإضافية مرتبطة بمستوى العضوية.' },
    audience: ['business_owner','provider'],
    tags: ['business','visibility'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/dashboard/businesses'], usableByAssistant: true, usableInMessages: false,
  },

  // ============================== PROVIDERS ==============================
  {
    id: 'prov-signup',
    type: 'faq', categoryId: 'providers',
    title: { ar: 'كيف أسجل كمزود خدمة؟' },
    body: { ar: 'افتح صفحة "للمزودين" واختر "ابدأ كمزود". أنشئ الحساب، اختر القطاع، ثم أكمل ملف المزود من لوحة التحكم.' },
    audience: ['visitor','provider'],
    tags: ['provider','onboarding','getting-started'], source: 'knowledge-seed-phase-2', status: 'published', priority: 90,
    relatedRoutes: ['/for-providers','/auth?mode=signup&role=provider'], usableByAssistant: true, usableInMessages: true,
  },
  {
    id: 'prov-complete-profile',
    type: 'faq', categoryId: 'providers',
    title: { ar: 'كيف أستكمل ملف المزود؟' },
    body: { ar: 'من لوحة المزود افتح "الملف"، أكمل الوصف، الخدمات، نطاق التغطية، أوقات العمل، والصور. الاكتمال يحسّن ظهور الملف في البحث.' },
    audience: ['provider'],
    tags: ['provider','onboarding'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/dashboard/provider/profile'], usableByAssistant: true, usableInMessages: false,
  },
  {
    id: 'prov-why-not-visible',
    type: 'faq', categoryId: 'providers',
    title: { ar: 'لماذا لا يظهر مزودي في البحث أو الصفحة العامة؟' },
    body: { ar: 'الأسباب الشائعة: نقص في بيانات الملف، عدم تفعيل خدمات، أو حالة الملف غير "منشور". تأكد من شريط اكتمال البيانات.' },
    audience: ['provider'],
    tags: ['provider','visibility','support'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/dashboard/provider/profile'], usableByAssistant: true, usableInMessages: false,
  },
  {
    id: 'prov-readiness',
    type: 'faq', categoryId: 'providers',
    title: { ar: 'ما شروط جاهزية المزود للتشغيل؟' },
    body: { ar: 'الجاهزية تتطلب: ملف مكتمل، خدمات معرَّفة، مدن خدمة، وسيلة تواصل مفعّلة، وقبول شروط الاستخدام.' },
    audience: ['provider'],
    tags: ['provider','readiness'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/dashboard/provider/profile'], usableByAssistant: true, usableInMessages: false,
  },
  {
    id: 'prov-receive-leads',
    type: 'faq', categoryId: 'providers',
    title: { ar: 'كيف أستقبل طلبات العملاء؟' },
    body: { ar: 'تظهر الطلبات المناسبة لخدماتك ومدن تغطيتك في "الفرص" داخل لوحة المزود. يمكنك مراجعة التفاصيل وتقديم عرض سعر.' },
    audience: ['provider'],
    tags: ['provider','rfq','quote'], source: 'knowledge-seed-phase-2', status: 'published', priority: 85,
    relatedRoutes: ['/dashboard/opportunities'], usableByAssistant: true, usableInMessages: true,
  },

  // ============================== QUOTE REQUESTS ==============================
  {
    id: 'rfq-what-is-request',
    type: 'faq', categoryId: 'quote-requests',
    title: { ar: 'ما هو طلب عرض السعر؟' },
    summary: { ar: 'طلب يصف احتياجك ليتم إرساله للمزودين المناسبين لتقديم عروض.' },
    body: { ar: 'يمكنك من خلال طلب عرض السعر توضيح نوع العمل، المدينة، التفاصيل، وإرفاق الملفات عند الحاجة. بعد الإرسال يظهر الطلب في لوحة التحكم ويمكن متابعة حالته.' },
    audience: ['customer','business_owner','provider'],
    tags: ['rfq','quote'], source: 'knowledge-seed-phase-2', status: 'published', priority: 95,
    relatedRoutes: ['/quote','/dashboard/my-requests'], usableByAssistant: true, usableInMessages: true,
  },
  {
    id: 'rfq-statuses',
    type: 'faq', categoryId: 'quote-requests',
    title: { ar: 'ما حالات الطلب؟' },
    body: { ar: 'الحالات الأساسية: قيد المراجعة، تم الإرسال للمزودين، استلم عروضًا، تم اختيار عرض، مغلق. الحالة تظهر بجانب الطلب في لوحة التحكم.' },
    audience: ['customer','provider'],
    tags: ['rfq','quote'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/dashboard/my-requests'], usableByAssistant: true, usableInMessages: false,
  },
  {
    id: 'rfq-attach-files',
    type: 'faq', categoryId: 'quote-requests',
    title: { ar: 'هل يمكن إرفاق ملفات؟' },
    body: { ar: 'نعم. يمكنك إرفاق صور أو رسومات أو مستندات داخل خطوة "التفاصيل" أثناء إنشاء الطلب لمساعدة المزود على تقدير العمل بدقة.' },
    audience: ['customer'],
    tags: ['rfq','files'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/quote'], usableByAssistant: true, usableInMessages: false,
  },
  {
    id: 'rfq-when-contacted',
    type: 'faq', categoryId: 'quote-requests',
    title: { ar: 'متى يتم التواصل معي؟' },
    body: { ar: 'يبدأ المزودون بمراجعة الطلب فور إرساله. مدة الرد تختلف حسب القطاع والمدينة ومدى توفر المزودين، وعادةً تكون خلال أيام قليلة.' },
    audience: ['customer'],
    tags: ['rfq','support'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/dashboard/my-requests'], usableByAssistant: true, usableInMessages: true,
  },
  {
    id: 'rfq-no-reply',
    type: 'faq', categoryId: 'quote-requests',
    title: { ar: 'لماذا لم يصلني رد بعد؟' },
    body: { ar: 'قد يكون عدد المزودين في قطاعك أو مدينتك محدودًا، أو أن التفاصيل تحتاج توضيحًا. جرّب تحديث الطلب بإضافة معلومات أو صور، أو تواصل مع الدعم.' },
    audience: ['customer'],
    tags: ['rfq','support'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/help/report-issue'], usableByAssistant: true, usableInMessages: false,
  },

  // ============================== PROJECTS & SITES ==============================
  {
    id: 'proj-site-vs-project',
    type: 'faq', categoryId: 'projects-sites',
    title: { ar: 'ما الفرق بين الموقع والمشروع؟' },
    body: { ar: 'الموقع هو نقطة جغرافية فعلية (عنوان/إحداثيات)، والمشروع هو عمل تنفيذي يتم على موقع أو أكثر. يمكن ربط عدة مشاريع بنفس الموقع.' },
    audience: ['customer','business_owner'],
    tags: ['projects','sites'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/dashboard/sites','/dashboard/projects'], usableByAssistant: true, usableInMessages: false,
  },
  {
    id: 'proj-personal-vs-business',
    type: 'faq', categoryId: 'projects-sites',
    title: { ar: 'هل المشاريع الشخصية تختلف عن مشاريع المنشأة؟' },
    body: { ar: 'نعم. المشروع الشخصي يخصك أنت كمستخدم، بينما مشروع المنشأة مرتبط بفريق المنشأة وصلاحياتها.' },
    audience: ['customer','business_owner'],
    tags: ['projects'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/dashboard/projects'], usableByAssistant: true, usableInMessages: false,
  },
  {
    id: 'proj-link-site',
    type: 'faq', categoryId: 'projects-sites',
    title: { ar: 'كيف أربط المشروع بموقع؟' },
    body: { ar: 'أثناء إنشاء المشروع أو تعديله ستجد حقل "الموقع". اختر موقعًا قائمًا أو أنشئ موقعًا جديدًا من نفس الشاشة.' },
    audience: ['customer','business_owner'],
    tags: ['projects','sites'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/dashboard/projects'], usableByAssistant: true, usableInMessages: false,
  },
  {
    id: 'proj-use-in-rfq',
    type: 'faq', categoryId: 'projects-sites',
    title: { ar: 'كيف أستخدم المشروع في طلب عرض سعر؟' },
    body: { ar: 'عند إنشاء طلب عرض سعر اختر "ربط بمشروع قائم" لتعبئة بياناته تلقائيًا في الطلب، مما يسرّع التقديم.' },
    audience: ['customer','business_owner'],
    tags: ['projects','rfq'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/quote'], usableByAssistant: true, usableInMessages: false,
  },

  // ============================== OFFERS & PRICING ==============================
  {
    id: 'offer-receive',
    type: 'faq', categoryId: 'offers-pricing',
    title: { ar: 'كيف أستقبل التسعيرات؟' },
    body: { ar: 'تظهر العروض داخل الطلب في لوحة التحكم. ستصلك إشعارات بكل عرض جديد، وتستطيع فتحه ومقارنته بسهولة.' },
    audience: ['customer'],
    tags: ['offers','quote'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/dashboard/my-requests'], usableByAssistant: true, usableInMessages: true,
  },
  {
    id: 'offer-compare',
    type: 'faq', categoryId: 'offers-pricing',
    title: { ar: 'كيف أقارن العروض؟' },
    body: { ar: 'افتح الطلب لعرض جميع العروض جنبًا إلى جنب مع التفاصيل والأسعار والمدد، مما يسهل اتخاذ القرار.' },
    audience: ['customer'],
    tags: ['offers','quote'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/dashboard/my-requests'], usableByAssistant: true, usableInMessages: false,
  },
  {
    id: 'offer-accept-equals-award',
    type: 'faq', categoryId: 'offers-pricing',
    title: { ar: 'هل قبول العرض يعني تعميدًا؟' },
    body: { ar: 'قبول العرض هو الخطوة الأولى للتعميد، لكنه لا يصبح ملزمًا إلا بعد توقيع العقد الإلكتروني بين الطرفين.' },
    audience: ['customer','provider'],
    tags: ['offers','contracts'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/dashboard/contracts'], usableByAssistant: true, usableInMessages: false,
  },
  {
    id: 'offer-becomes-contract',
    type: 'faq', categoryId: 'offers-pricing',
    title: { ar: 'متى يتحول العرض إلى عقد؟' },
    body: { ar: 'بعد قبول العرض يتم توليد مسودة عقد. عند توقيع الطرفين عليها إلكترونيًا يصبح العقد ساريًا.' },
    audience: ['customer','provider'],
    tags: ['offers','contracts'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/dashboard/contracts'], usableByAssistant: true, usableInMessages: false,
  },

  // ============================== CONTRACTS ==============================
  {
    id: 'contract-what-is-award',
    type: 'faq', categoryId: 'contracts',
    title: { ar: 'ما هو التعميد؟' },
    body: { ar: 'التعميد هو الاتفاق الرسمي بين العميل والمزود على تنفيذ العرض المتفق عليه، ويتم توثيقه بعقد إلكتروني داخل المنصة.' },
    audience: ['customer','provider','business_owner'],
    tags: ['contracts'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/dashboard/contracts'], usableByAssistant: true, usableInMessages: false,
  },
  {
    id: 'contract-stages',
    type: 'faq', categoryId: 'contracts',
    title: { ar: 'ما مراحل العقد؟' },
    body: { ar: 'المراحل الأساسية: مسودة، توقيع الطرفين، تنفيذ، تسليم، إغلاق. يمكن متابعة المرحلة من ملف العقد.' },
    audience: ['customer','provider'],
    tags: ['contracts'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/dashboard/contracts'], usableByAssistant: true, usableInMessages: false,
  },
  {
    id: 'contract-mutual-approval',
    type: 'faq', categoryId: 'contracts',
    title: { ar: 'كيف تتم الموافقة بين الطرفين؟' },
    body: { ar: 'تتم الموافقة بالتوقيع الإلكتروني داخل ملف العقد. لا يصبح العقد نافذًا إلا بعد توقيع الطرفين.' },
    audience: ['customer','provider'],
    tags: ['contracts'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/dashboard/contracts'], usableByAssistant: true, usableInMessages: false,
  },
  {
    id: 'contract-where-found',
    type: 'faq', categoryId: 'contracts',
    title: { ar: 'أين أجد العقود؟' },
    body: { ar: 'من لوحة التحكم اختر "العقود" لعرض كل عقودك مع حالتها وتاريخ توقيعها.' },
    audience: ['customer','provider'],
    tags: ['contracts'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/dashboard/contracts'], usableByAssistant: true, usableInMessages: false,
  },

  // ============================== PAYMENTS ==============================
  {
    id: 'pay-in-platform',
    type: 'faq', categoryId: 'payments',
    title: { ar: 'هل الدفع متاح داخل المنصة؟' },
    body: { ar: 'بعض مدفوعات الاشتراكات تتم داخل المنصة. مدفوعات تنفيذ العقود تختلف حسب الاتفاق بين الطرفين، ويُنصح بتوثيقها في العقد.' },
    audience: ['customer','provider','business_owner'],
    tags: ['payment'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/dashboard/billing'], usableByAssistant: true, usableInMessages: false,
  },
  {
    id: 'pay-invoices',
    type: 'faq', categoryId: 'payments',
    title: { ar: 'أين أجد الفواتير؟' },
    body: { ar: 'من لوحة التحكم افتح "الفوترة" لعرض فواتير الاشتراكات والمدفوعات المسجلة داخل المنصة.' },
    audience: ['customer','provider','business_owner'],
    tags: ['payment'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/dashboard/billing'], usableByAssistant: true, usableInMessages: false,
  },
  {
    id: 'pay-failed',
    type: 'faq', categoryId: 'payments',
    title: { ar: 'ماذا أفعل عند فشل الدفع؟' },
    body: { ar: 'تأكد من بيانات بطاقتك وتوفر الرصيد. أعد المحاولة، وإذا استمرت المشكلة تواصل مع الدعم مع رقم العملية وتاريخها.' },
    audience: ['customer','provider'],
    tags: ['payment','support'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/help/report-issue'], usableByAssistant: true, usableInMessages: false,
  },
  {
    id: 'pay-membership-invoices',
    type: 'faq', categoryId: 'payments',
    title: { ar: 'هل توجد فواتير عضوية؟' },
    body: { ar: 'نعم. عند ترقية أو تجديد العضوية تُنشأ فاتورة تظهر في "الفوترة" مع تفاصيل الباقة والمدة.' },
    audience: ['provider','business_owner'],
    tags: ['payment','membership'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/dashboard/billing'], usableByAssistant: true, usableInMessages: false,
  },

  // ============================== MEMBERSHIPS ==============================
  {
    id: 'mem-free',
    type: 'faq', categoryId: 'memberships',
    title: { ar: 'ما هي العضوية المجانية؟' },
    body: { ar: 'العضوية المجانية تتيح للمزود إنشاء ملف أساسي واستقبال عدد محدود من الفرص. تظهر حدود الاستخدام داخل لوحة التحكم.' },
    audience: ['provider','business_owner'],
    tags: ['membership'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/membership'], usableByAssistant: true, usableInMessages: false,
  },
  {
    id: 'mem-plans-diff',
    type: 'faq', categoryId: 'memberships',
    title: { ar: 'ما الفرق بين الباقات؟' },
    body: { ar: 'تختلف الباقات في عدد الفروع، عدد الفرص، أولوية الظهور، والميزات الإدارية. تفاصيل كل باقة في صفحة العضويات.' },
    audience: ['provider','business_owner'],
    tags: ['membership','pricing'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/membership'], usableByAssistant: true, usableInMessages: false,
  },
  {
    id: 'mem-track-limits',
    type: 'faq', categoryId: 'memberships',
    title: { ar: 'أين أتابع حدود الاستخدام؟' },
    body: { ar: 'من لوحة التحكم > "العضوية" تجد عدّاد الفرص المتبقية وعدد الفروع المسموح بها حسب باقتك.' },
    audience: ['provider','business_owner'],
    tags: ['membership'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/dashboard/membership'], usableByAssistant: true, usableInMessages: false,
  },
  {
    id: 'mem-upgrade',
    type: 'faq', categoryId: 'memberships',
    title: { ar: 'كيف أطور العضوية؟' },
    body: { ar: 'افتح صفحة "العضوية" واختر الباقة المناسبة ثم أكمل خطوات الدفع. تُفعَّل الباقة الجديدة فور إتمام العملية.' },
    audience: ['provider','business_owner'],
    tags: ['membership','payment'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/membership'], usableByAssistant: true, usableInMessages: false,
  },

  // ============================== SECURITY & PRIVACY ==============================
  {
    id: 'sec-who-sees-data',
    type: 'faq', categoryId: 'security-privacy',
    title: { ar: 'من يستطيع رؤية بياناتي؟' },
    body: { ar: 'بياناتك الشخصية ليست عامة. عند إرسال طلب عرض سعر، يطّلع المزودون على معلومات الطلب الضرورية فقط للتواصل وتقديم العرض.' },
    audience: ['visitor','customer','provider','business_owner'],
    tags: ['privacy','security'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/privacy'], usableByAssistant: true, usableInMessages: false,
  },
  {
    id: 'sec-files-private',
    type: 'faq', categoryId: 'security-privacy',
    title: { ar: 'هل ملفاتي خاصة؟' },
    body: { ar: 'الملفات المرفقة بطلب أو عقد متاحة فقط لأطراف الطلب أو العقد. لا تُعرض للعامة.' },
    audience: ['customer','provider'],
    tags: ['privacy','security','files'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/privacy'], usableByAssistant: true, usableInMessages: false,
  },
  {
    id: 'sec-protect-account',
    type: 'faq', categoryId: 'security-privacy',
    title: { ar: 'كيف أحمي حسابي؟' },
    body: { ar: 'استخدم كلمة مرور قوية، لا تشاركها مع أحد، وتحقق من البريد المرتبط بالحساب. سجّل الخروج من الأجهزة العامة بعد الاستخدام.' },
    audience: ['customer','provider','business_owner'],
    tags: ['security','account'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/dashboard/settings'], usableByAssistant: true, usableInMessages: false,
  },
  {
    id: 'sec-team-permissions',
    type: 'faq', categoryId: 'security-privacy',
    title: { ar: 'كيف تعمل صلاحيات الفريق؟' },
    body: { ar: 'كل عضو في فريق المنشأة يحصل على دور محدد (مالك، مدير، موظف). الدور يحدد ما يمكن للعضو رؤيته أو تعديله داخل المنشأة.' },
    audience: ['business_owner'],
    tags: ['security','team'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/dashboard/businesses'], usableByAssistant: true, usableInMessages: false,
  },

  // ============================== ACCOUNT ==============================
  {
    id: 'acc-create',
    type: 'faq', categoryId: 'account',
    title: { ar: 'كيف أنشئ حسابًا؟' },
    body: { ar: 'افتح صفحة تسجيل الدخول واختر "إنشاء حساب"، أدخل بريدك ورقمك وكلمة المرور، ثم فعّل الحساب من رابط التحقق في البريد.' },
    audience: ['visitor'],
    tags: ['account','onboarding'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/auth'], usableByAssistant: true, usableInMessages: false,
  },
  {
    id: 'acc-verify-email',
    type: 'faq', categoryId: 'account',
    title: { ar: 'كيف أتحقق من البريد؟' },
    body: { ar: 'بعد التسجيل ستصلك رسالة فيها رابط تحقق. إذا لم تصل تأكد من مجلد "غير المرغوب" أو اطلب إعادة الإرسال من صفحة التحقق.' },
    audience: ['customer','provider'],
    tags: ['account','verification'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/auth/verified','/help/email-not-arriving'], usableByAssistant: true, usableInMessages: false,
  },
  {
    id: 'acc-reset-password',
    type: 'faq', categoryId: 'account',
    title: { ar: 'كيف أستعيد كلمة المرور؟' },
    body: { ar: 'من صفحة تسجيل الدخول اختر "نسيت كلمة المرور"، أدخل بريدك، وستصلك رسالة فيها رابط لإعادة التعيين.' },
    audience: ['visitor','customer','provider'],
    tags: ['account','security'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/auth'], usableByAssistant: true, usableInMessages: false,
  },
  {
    id: 'acc-edit-profile',
    type: 'faq', categoryId: 'account',
    title: { ar: 'كيف أعدل بياناتي؟' },
    body: { ar: 'افتح "الإعدادات" من لوحة التحكم، عدّل بياناتك (الاسم، الجوال، اللغة، البريد) ثم احفظ التغييرات.' },
    audience: ['customer','provider','business_owner'],
    tags: ['account'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/dashboard/settings'], usableByAssistant: true, usableInMessages: false,
  },

  // ============================== SUPPORT ==============================
  {
    id: 'sup-contact',
    type: 'faq', categoryId: 'support',
    title: { ar: 'كيف أتواصل مع الدعم؟' },
    body: { ar: 'من مركز المساعدة اختر "الإبلاغ عن مشكلة"، أو راسلنا عبر صفحة "تواصل معنا". فريق الدعم يرد عبر البريد المسجل لديك.' },
    audience: ['customer','provider','business_owner'],
    tags: ['support'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/help/report-issue','/contact'], usableByAssistant: true, usableInMessages: true,
  },
  {
    id: 'sup-info-to-send',
    type: 'faq', categoryId: 'support',
    title: { ar: 'ما المعلومات التي يجب إرسالها عند وجود مشكلة؟' },
    body: { ar: 'أرسل وصفًا للمشكلة، الخطوات لإعادة إنتاجها، وقت حدوثها، رقم الطلب أو العقد إن وجد، ولقطة شاشة لو أمكن.' },
    audience: ['customer','provider'],
    tags: ['support'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/help/report-issue'], usableByAssistant: true, usableInMessages: false,
  },
  {
    id: 'sup-file-upload-issue',
    type: 'faq', categoryId: 'support',
    title: { ar: 'ماذا أفعل إذا واجهت مشكلة في رفع الملفات؟' },
    body: { ar: 'تأكد من حجم الملف ونوعه (يفضل صور بصيغة JPG/PNG أو PDF). جرّب اتصالًا أسرع، وإن استمرت المشكلة أرسل تفاصيلها للدعم.' },
    audience: ['customer','provider'],
    tags: ['support','files'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/help/report-issue'], usableByAssistant: true, usableInMessages: false,
  },
  {
    id: 'sup-no-notifications',
    type: 'faq', categoryId: 'support',
    title: { ar: 'ماذا أفعل إذا لم تصلني الإشعارات؟' },
    body: { ar: 'افتح "الإعدادات" وتأكد من تفعيل الإشعارات والبريد. راجع مجلد "غير المرغوب" في البريد، وأضف عنوان قطاعات إلى جهات الاتصال الموثوقة.' },
    audience: ['customer','provider'],
    tags: ['support','notifications'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/dashboard/settings'], usableByAssistant: true, usableInMessages: false,
  },

  // ============================== DISPUTES ==============================
  {
    id: 'dis-file-complaint',
    type: 'faq', categoryId: 'disputes',
    title: { ar: 'كيف أقدم شكوى؟' },
    body: { ar: 'افتح "الإبلاغ عن مشكلة" واختر النوع (شكوى)، اشرح الموضوع بدقة وأرفق ما يدعمه (رسائل، فواتير، صور). سيتم فتح بلاغ ومتابعته.' },
    audience: ['customer','provider','business_owner'],
    tags: ['support','disputes'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/help/report-issue'], usableByAssistant: true, usableInMessages: false,
  },
  {
    id: 'dis-track',
    type: 'faq', categoryId: 'disputes',
    title: { ar: 'كيف أتابع الشكوى؟' },
    body: { ar: 'تصلك تحديثات الشكوى عبر البريد والإشعارات. كذلك يمكنك متابعتها من صفحة "الدعم" في لوحة التحكم.' },
    audience: ['customer','provider'],
    tags: ['support','disputes'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/dashboard'], usableByAssistant: true, usableInMessages: false,
  },
  {
    id: 'dis-contract-disagreement',
    type: 'faq', categoryId: 'disputes',
    title: { ar: 'ماذا أفعل عند وجود خلاف على عرض أو عقد؟' },
    body: { ar: 'تواصل أولًا مع الطرف الآخر داخل المنصة لتوثيق المحادثة. إذا لم يحل الخلاف، افتح بلاغًا للدعم وأرفق العقد أو العرض موضوع الخلاف.' },
    audience: ['customer','provider','business_owner'],
    tags: ['disputes','contracts'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/help/report-issue','/dashboard/contracts'], usableByAssistant: true, usableInMessages: false,
  },

  // ============================== POLICY SUMMARIES ==============================
  {
    id: 'policy-privacy-summary',
    type: 'policy', categoryId: 'security-privacy',
    title: { ar: 'سياسة الخصوصية — ملخص', en: 'Privacy policy — summary' },
    summary: { ar: 'كيف نتعامل مع بياناتك ومعلومات حسابك في قطاعات.' },
    body: { ar: 'نلتزم بحماية بياناتك. لا نشارك معلوماتك مع أطراف ثالثة دون موافقتك ما عدا ما يلزم لتنفيذ الخدمة. راجع السياسة الكاملة لمعرفة التفاصيل.' },
    audience: ['visitor','customer','provider','business_owner'],
    tags: ['privacy','policy'], source: 'src/pages/Privacy.tsx', status: 'published',
    relatedRoutes: ['/privacy'], usableByAssistant: true, usableInMessages: false,
  },
  {
    id: 'policy-terms-summary',
    type: 'policy', categoryId: 'security-privacy',
    title: { ar: 'شروط الاستخدام — ملخص', en: 'Terms of use — summary' },
    body: { ar: 'باستخدامك قطاعات فإنك توافق على شروط الاستخدام التي تنظم العلاقة بين المنصة والمستخدم.' },
    audience: ['visitor','customer','provider','business_owner'],
    tags: ['terms','policy'], source: 'src/pages/Terms.tsx', status: 'published',
    relatedRoutes: ['/terms'], usableByAssistant: true, usableInMessages: false,
  },

  // ============================== MESSAGE TEMPLATES ==============================
  {
    id: 'msg-quote-received-customer',
    type: 'message_template', categoryId: 'quote-requests',
    title: { ar: 'إشعار: استلام عرض سعر جديد', en: 'Notice: new quote received' },
    body: { ar: 'لديك عرض سعر جديد على طلبك. يمكنك مراجعته ومقارنته بالعروض الأخرى من لوحة التحكم.' },
    audience: ['customer'],
    tags: ['quote','rfq'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/dashboard/my-requests'],
    usableByAssistant: false, usableInMessages: true,
  },
  {
    id: 'msg-quote-request-provider',
    type: 'message_template', categoryId: 'quote-requests',
    title: { ar: 'إشعار: طلب عرض سعر جديد', en: 'Notice: new quote request' },
    body: { ar: 'يوجد طلب عرض سعر مناسب لخدماتك. ادخل لوحة التحكم لمراجعة التفاصيل والرد.' },
    audience: ['provider'],
    tags: ['quote','rfq','provider'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/dashboard/opportunities'],
    usableByAssistant: false, usableInMessages: true,
  },
  {
    id: 'msg-contract-signed',
    type: 'message_template', categoryId: 'contracts',
    title: { ar: 'إشعار: تم توقيع العقد' },
    body: { ar: 'تم توقيع العقد من الطرفين. يمكنك متابعة مراحل التنفيذ من ملف العقد في لوحة التحكم.' },
    audience: ['customer','provider'],
    tags: ['contracts'], source: 'knowledge-seed-phase-2', status: 'published',
    relatedRoutes: ['/dashboard/contracts'],
    usableByAssistant: false, usableInMessages: true,
  },

  // ============================== INTERNAL OPERATIONS ==============================
  {
    id: 'ops-review-new-rfq',
    type: 'internal_note', categoryId: 'internal-ops',
    title: { ar: 'كيف يتم فحص طلب RFQ جديد؟' },
    body: { ar: 'تحقق من اكتمال البيانات، صحة المدينة، نوع القطاع، ووجود المرفقات إن لزم. وضّح للمزودين أي معلومة ناقصة قبل توجيه الطلب.' },
    audience: ['admin','operations'],
    tags: ['support','rfq'], source: 'knowledge-seed-phase-2', status: 'internal',
    usableByAssistant: false, usableInMessages: false,
  },
  // Placeholder — real entry continues below.
  {
    id: 'ops-review-new-rfq-DUPLICATE_SENTINEL_DO_NOT_USE',
    type: 'internal_note', categoryId: 'internal-ops',
    title: { ar: 'sentinel' },
    body: { ar: 'تحقق من اكتمال البيانات، صحة المدينة، نوع القطاع، ووجود المرفقات إن لزم. وضّح للمزودين أي معلومة ناقصة قبل توجيه الطلب.' },
    audience: ['admin','operations'],
    tags: ['support','rfq'], source: 'knowledge-seed-phase-2', status: 'internal',
    usableByAssistant: false, usableInMessages: false,
  },
  {
    id: 'ops-review-provider-readiness',
    type: 'internal_note', categoryId: 'internal-ops',
    title: { ar: 'كيف يتم فحص جاهزية مزود؟' },
    body: { ar: 'افحص ملف المزود: الخدمات، المدن، طرق التواصل، حالة الاشتراك، ووجود توثيق إن لزم. لا تنشر المزود قبل اكتمال الحد الأدنى.' },
    audience: ['admin','operations'],
    tags: ['provider','readiness'], source: 'knowledge-seed-phase-2', status: 'internal',
    usableByAssistant: false, usableInMessages: false,
  },
  {
    id: 'ops-incomplete-provider',
    type: 'internal_note', categoryId: 'internal-ops',
    title: { ar: 'كيف يتم التعامل مع مزود ناقص بيانات؟' },
    body: { ar: 'تواصل مع المزود عبر القناة الموثقة، حدد الحقول الناقصة بدقة، وامنحه مهلة معقولة. لا ترفع حالة الجاهزية قبل التحقق.' },
    audience: ['admin','operations'],
    tags: ['provider','support'], source: 'knowledge-seed-phase-2', status: 'internal',
    usableByAssistant: false, usableInMessages: false,
  },
  {
    id: 'ops-do-not-share',
    type: 'internal_note', categoryId: 'internal-ops',
    title: { ar: 'ما المعلومات التي لا يجب مشاركتها مع المستخدم؟' },
    body: { ar: 'لا تشارك معلومات داخلية عن تشغيل النظام، تفاصيل قواعد بيانات، تفاصيل مزودين آخرين، أو أرقام حالات أمنية. التزم بالردود المعتمدة فقط.' },
    audience: ['admin','operations'],
    tags: ['security','support'], source: 'knowledge-seed-phase-2', status: 'internal',
    usableByAssistant: false, usableInMessages: false,
  },
  {
    id: 'ops-support-escalation',
    type: 'internal_note', categoryId: 'internal-ops',
    title: { ar: 'تصعيد الدعم — تشغيل داخلي', en: 'Support escalation — internal' },
    body: { ar: 'الحالات المتعلقة بالدفع تُحوَّل إلى فريق المالية خلال 24 ساعة عبر مركز التشغيل.' },
    audience: ['admin','operations'],
    tags: ['support','payment'], source: 'docs/pilot-launch-operations.md', status: 'internal',
    usableByAssistant: false, usableInMessages: false,
  },
];

export const knowledgeRegistry: readonly KnowledgeItem[] = Object.freeze(ITEMS);

export function listKnowledgeItems(): readonly KnowledgeItem[] {
  return knowledgeRegistry;
}

export function getKnowledgeItem(id: string): KnowledgeItem | undefined {
  return knowledgeRegistry.find((it) => it.id === id);
}

export function listByCategory(categoryId: string): KnowledgeItem[] {
  return knowledgeRegistry.filter((it) => it.categoryId === categoryId);
}