import React from 'react';
import { useLanguage } from '@/i18n/LanguageContext';
import { usePageMeta } from '@/hooks/usePageMeta';
import { Navbar } from '@/components/layout/Navbar';
import { Footer } from '@/components/layout/Footer';

const Privacy = () => {
  const { isRTL } = useLanguage();
  usePageMeta({ title: isRTL ? 'سياسة الخصوصية | قِطاعات' : 'Privacy Policy | Qitaat', description: isRTL ? 'سياسة الخصوصية لمنصة قِطاعات' : 'Qitaat platform privacy policy' });

  return (
    <div className="min-h-screen bg-background">
      <Navbar />
      <div className="bg-primary pt-24 pb-10"><div className="container px-4"><h1 className="font-heading text-2xl sm:text-3xl font-bold text-primary-foreground">{isRTL ? 'سياسة الخصوصية' : 'Privacy Policy'}</h1></div></div>
      <div className="container py-10 px-4 max-w-3xl prose prose-sm dark:prose-invert">
        <h2>{isRTL ? 'جمع المعلومات' : 'Information Collection'}</h2>
        <p>{isRTL ? 'نقوم بجمع المعلومات التي تقدمها لنا مباشرة عند التسجيل أو استخدام خدماتنا، بما في ذلك الاسم والبريد الإلكتروني ورقم الهاتف ومعلومات العمل.' : 'We collect information you provide directly when registering or using our services, including name, email, phone number and business information.'}</p>
        <h2>{isRTL ? 'استخدام المعلومات' : 'Use of Information'}</h2>
        <p>{isRTL ? 'نستخدم المعلومات لتوفير وتحسين خدماتنا، والتواصل معك، وضمان أمان المنصة.' : 'We use information to provide and improve our services, communicate with you, and ensure platform security.'}</p>
        <h2>{isRTL ? 'حماية المعلومات' : 'Information Protection'}</h2>
        <p>{isRTL ? 'نتخذ إجراءات أمنية مناسبة لحماية معلوماتك الشخصية من الوصول غير المصرح به أو التغيير أو الإفصاح.' : 'We take appropriate security measures to protect your personal information from unauthorized access, alteration or disclosure.'}</p>
        <h2>{isRTL ? 'ملفات تعريف الارتباط' : 'Cookies'}</h2>
        <p>{isRTL ? 'نستخدم ملفات تعريف الارتباط لتحسين تجربة الاستخدام وتحليل حركة المرور على الموقع.' : 'We use cookies to improve user experience and analyze website traffic.'}</p>
        <h2>{isRTL ? 'تنظيف التخزين القديم (faneen.com)' : 'Legacy Storage Cleanup (faneen.com)'}</h2>
        <p>{isRTL ? 'كان الموقع يعمل سابقاً تحت اسم النطاق faneen.com وكان يخزّن بعض البيانات محلياً في متصفحك بادئتها "faneen_" (مثل تفضيلات اللغة، سجل البحث، إعدادات الواجهة). بعد الانتقال إلى قِطاعات (qitaat.com) وإيقاف نظام الترحيل التجريبي، يقوم الموقع بتشغيل سكربت تنظيف لمرة واحدة عند زيارتك التالية يحذف تلقائياً جميع المفاتيح التي تبدأ بـ "faneen_" من localStorage و sessionStorage و الكوكيز الخاصة بالنطاق. هذه العملية تتم بالكامل داخل متصفحك، ولا يتم إرسال أي من هذه البيانات إلى خوادمنا قبل حذفها، ويتم تعيين علامة (qitaat_legacy_cleanup_v1_done) لمنع تكرار العملية.' : 'The site previously operated under the faneen.com domain and stored some data locally in your browser prefixed with "faneen_" (e.g. language preferences, search history, UI settings). After migrating to Qitaat (qitaat.com) and discontinuing the experimental migration system, the site runs a one-time cleanup script on your next visit that automatically removes all keys prefixed with "faneen_" from localStorage, sessionStorage, and domain cookies. This happens entirely within your browser — none of this data is sent to our servers before deletion — and a flag (qitaat_legacy_cleanup_v1_done) is set to prevent the cleanup from running again.'}</p>
        <h2>{isRTL ? 'إزالة نظام القياس التجريبي (Telemetry)' : 'Removal of Experimental Telemetry'}</h2>
        <p>{isRTL ? 'تم حذف نظام تتبع الترحيل التجريبي بالكامل، بما في ذلك جداول التتبع، تقارير التشغيل، إشعارات الفشل، وسجلات إعادة التشغيل. لم يعد الموقع يجمع أي بيانات تتعلق بترحيل التخزين المحلي. أي بيانات سابقة تم إنتاجها من هذا النظام أثناء الفترة التجريبية تم حذفها من قاعدة البيانات.' : 'The experimental migration telemetry system has been fully removed, including its tracking tables, run reports, failure alerts, and rerun history. The site no longer collects any data related to local-storage migrations. Any prior data generated by this system during the beta period has been deleted from our database.'}</p>
        <h2>{isRTL ? 'بيانات الأداء (Core Web Vitals)' : 'Performance Data (Core Web Vitals)'}</h2>
        <p>{isRTL ? 'لتحسين سرعة الموقع، نقوم بجمع مقاييس أداء مجهولة الهوية (LCP، CLS، INP، FCP، TTFB) من المتصفح، إضافة إلى مسار الصفحة ونوع الجهاز (جوال/سطح مكتب). لا تتضمن هذه البيانات أي معرّف شخصي أو عنوان IP أو محتوى تتصفحه. يتم إرسالها عبر تقنية sendBeacon دون تعطيل التنقل، وتُستخدم حصرياً داخل لوحة الإدارة لقياس صحة الأداء. لا نشغّل هذا التتبع داخل بيئة معاينة Lovable.' : 'To improve site speed we collect anonymous performance metrics (LCP, CLS, INP, FCP, TTFB) from your browser, along with the page path and device type (mobile/desktop). This data contains no personal identifiers, IP address, or browsing content. It is sent via sendBeacon without blocking navigation and is used exclusively inside our admin panel to monitor performance health. This tracking is disabled inside the Lovable preview environment.'}</p>
        <h2>{isRTL ? 'تدقيق الموقع (SEO Audit)' : 'Site Audit (SEO)'}</h2>
        <p>{isRTL ? 'يقوم النظام بتدقيق دوري (يومي) لصحة الموقع يشمل التحقق من ملفات robots.txt و sitemap.xml ووسوم meta على صفحاتنا العامة فقط. لا يجمع هذا التدقيق أي بيانات عن الزوار.' : 'The system performs a periodic (daily) site-health audit covering robots.txt, sitemap.xml, and meta tags on our public pages only. This audit collects no visitor data.'}</p>
        <h2>{isRTL ? 'حقوقك' : 'Your Rights'}</h2>
        <p>{isRTL ? 'يمكنك طلب الاطلاع على بياناتك الشخصية أو تصحيحها أو حذفها في أي وقت عبر التواصل معنا. كما يمكنك مسح بيانات المتصفح يدوياً من إعدادات المتصفح.' : 'You may request access, correction, or deletion of your personal data at any time by contacting us. You can also clear browser-stored data manually from your browser settings.'}</p>
        <h2>{isRTL ? 'التواصل' : 'Contact'}</h2>
        <p>{isRTL ? 'لأي استفسارات حول سياسة الخصوصية، يرجى التواصل معنا على info@qitaat.com' : 'For any privacy policy inquiries, please contact us at info@qitaat.com'}</p>
      </div>
      <Footer />
    </div>
  );
};

export default Privacy;
