// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-providers.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
var search_providers_default = defineTool({
  name: "search_providers",
  title: "Search providers",
  description: "Search Qitaat industrial service providers by keyword. Returns public directory entries (name, city, slug).",
  inputSchema: {
    query: z.string().trim().min(1).describe("Keyword to match against provider name (Arabic or English)."),
    limit: z.number().int().min(1).max(25).optional().describe("Max results (default 10).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, limit }) => {
    const url = process.env.SUPABASE_URL;
    const anon = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    if (!url || !anon) {
      return { content: [{ type: "text", text: "Backend not configured." }], isError: true };
    }
    const n = limit ?? 10;
    const like = encodeURIComponent(`*${query}*`);
    const endpoint = `${url}/rest/v1/businesses_public?or=(name_ar.ilike.${like},name_en.ilike.${like})&limit=${n}&select=id,slug,name_ar,name_en,city_ar,city_en`;
    const res = await fetch(endpoint, {
      headers: { apikey: anon, Authorization: `Bearer ${anon}` }
    });
    if (!res.ok) {
      return { content: [{ type: "text", text: `Search failed: HTTP ${res.status}` }], isError: true };
    }
    const rows = await res.json();
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { results: rows, count: rows.length }
    };
  }
});

// src/lib/mcp/tools/list-categories.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var list_categories_default = defineTool2({
  name: "list_categories",
  title: "List industrial categories",
  description: "List published Qitaat taxonomy categories (industrial sectors and services).",
  inputSchema: {
    limit: z2.number().int().min(1).max(100).optional().describe("Max results (default 50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const url = process.env.SUPABASE_URL;
    const anon = process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY;
    if (!url || !anon) {
      return { content: [{ type: "text", text: "Backend not configured." }], isError: true };
    }
    const n = limit ?? 50;
    const endpoint = `${url}/rest/v1/taxonomy_categories?limit=${n}&select=id,slug,name_ar,name_en,parent_id`;
    const res = await fetch(endpoint, {
      headers: { apikey: anon, Authorization: `Bearer ${anon}` }
    });
    if (!res.ok) {
      return { content: [{ type: "text", text: `List failed: HTTP ${res.status}` }], isError: true };
    }
    const rows = await res.json();
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { categories: rows, count: rows.length }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "qitaat-mcp",
  title: "Qitaat Directory MCP",
  version: "0.1.0",
  instructions: "Read-only access to the Qitaat industrial B2B directory. Use `search_providers` to find providers by keyword and `list_categories` to browse the taxonomy.",
  tools: [search_providers_default, list_categories_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
