SET LOCAL session_replication_role = replica;
DELETE FROM public.platform_settings
WHERE setting_key IN (
  'SMTP_HOST','SMTP_PORT','SMTP_USER','SMTP_PASSWORD',
  'SENDER_EMAIL','SENDER_NAME',
  'TWILIO_ACCOUNT_SID','TWILIO_AUTH_TOKEN','TWILIO_VERIFY_SID',
  'OPENAI_API_KEY','GOOGLE_AI_KEY',
  'GOOGLE_MAPS_KEY','GOOGLE_ANALYTICS_ID',
  'GOOGLE_RECAPTCHA_KEY','GOOGLE_RECAPTCHA_SECRET',
  'FCM_SERVER_KEY'
);