
DO $$
DECLARE
  v_type_id uuid;
  v_kitchens_id uuid;
BEGIN
  SELECT id INTO v_type_id FROM public.taxonomy_types WHERE code = 'sector' LIMIT 1;
  IF v_type_id IS NULL THEN
    RAISE EXCEPTION 'taxonomy_types.sector not found';
  END IF;

  INSERT INTO public.taxonomy_categories (
    taxonomy_type_id, parent_id, slug, name_ar, name_en,
    short_description_ar, short_description_en,
    description_ar, description_en,
    seo_title_ar, seo_title_en, seo_description_ar, seo_description_en,
    keywords_ar, keywords_en, icon, color, sort_order,
    is_active, is_public, is_searchable, is_featured, is_archived,
    show_in_registration, show_in_search, show_in_seo, show_in_showcase,
    show_in_products, show_in_contracts, show_in_quotes, show_in_admin_only,
    metadata
  ) VALUES
  (v_type_id, NULL, 'aluminum', 'الألمنيوم', 'Aluminum',
   'قطاع الألمنيوم: أبواب، شبابيك، واجهات، مطابخ، وأقسام داخلية.',
   'Aluminum sector: doors, windows, facades, kitchens, partitions.',
   'يشمل قطاع الألمنيوم تصنيع وتركيب الأبواب والشبابيك والواجهات والكلادينج وأقسام الألمنيوم الداخلية والمطابخ والخزائن والمظلات وكافة منتجات البروفايلات والإكسسوارات المرتبطة بها.',
   'The aluminum sector covers fabrication and installation of doors, windows, façades, cladding, indoor partitions, kitchens, wardrobes, pergolas and all profile-based products.',
   'قطاع الألمنيوم في قِطاعات', 'Aluminum Sector on Qitaat',
   'دليل متخصصي الألمنيوم: أبواب وشبابيك وواجهات ومطابخ وأقسام داخلية مع أفضل الماركات.',
   'Directory of aluminum specialists: doors, windows, façades, kitchens and partitions.',
   ARRAY['ألمنيوم','أبواب ألمنيوم','شبابيك ألمنيوم','واجهات','مطابخ ألمنيوم','بروفايل','كلادينج','مظلات ألمنيوم'],
   ARRAY['aluminum','aluminum doors','aluminum windows','facades','aluminum kitchens','profiles','cladding','pergolas'],
   'PanelTop', '#3B82F6', 10,
   true,true,true,true,false, true,true,true,true,true,true,true,false,
   jsonb_build_object('sector_key','aluminum','industry','industrial')),

  (v_type_id, NULL, 'glass-securit', 'الزجاج والسيكوريت', 'Glass & Securit',
   'الزجاج المسطح، السيكوريت، الزجاج المعزول، والمرايا.',
   'Flat glass, tempered (Securit), insulated glass units, and mirrors.',
   'يشمل قطاع الزجاج والسيكوريت توريد وتصنيع وتركيب الزجاج المسطح والسيكوريت المقسى والزجاج المعشّق والمعزول والـ Low-E والمرايا وواجهات الزجاج الهيكلية والديكورات الزجاجية.',
   'Covers supply, processing and installation of float glass, tempered Securit, laminated, insulated (IGU), low-e glass, mirrors and structural glazing façades.',
   'قطاع الزجاج والسيكوريت', 'Glass & Securit Sector',
   'كل ما يخص الزجاج المسطح والمقسى والمعزول والمرايا والديكورات الزجاجية في مكان واحد.',
   'Everything about flat, tempered, insulated and decorative glass, mirrors and structural glazing.',
   ARRAY['زجاج','سيكوريت','زجاج مقسى','زجاج معزول','مرايا','واجهات زجاجية','زجاج لو إي'],
   ARRAY['glass','securit','tempered glass','insulated glass','mirrors','glass facades','low-e'],
   'GlassWater', '#06B6D4', 20,
   true,true,true,true,false, true,true,true,true,true,true,true,false,
   jsonb_build_object('sector_key','glass','industry','industrial')),

  (v_type_id, NULL, 'iron-steel', 'الحديد والصاج', 'Iron & Steel',
   'الحديد الإنشائي، صاج، أبواب ونوافذ حديد، بوابات وسواتر.',
   'Structural steel, sheet metal, iron doors and windows, gates and screens.',
   'يضم قطاع الحديد والصاج الحدادة الإنشائية والمعمارية، أبواب وشبابيك الحديد المشغول، البوابات، السواتر، الأدراج الحديدية، الهياكل المعدنية والورش المتخصصة.',
   'Includes structural and architectural steelwork, wrought-iron doors and windows, gates, screens, staircases and metal structures.',
   'قطاع الحديد والصاج', 'Iron & Steel Sector',
   'دليل الورش والمصانع المتخصصة في الحديد الإنشائي والأبواب والبوابات والسواتر.',
   'Directory of workshops and factories for structural steel, doors, gates and screens.',
   ARRAY['حديد','صاج','أبواب حديد','بوابات','سواتر حديد','حديد مشغول','هياكل معدنية'],
   ARRAY['iron','steel','steel doors','gates','metal screens','wrought iron','metal structures'],
   'Hammer', '#64748B', 30,
   true,true,true,true,false, true,true,true,true,true,true,true,false,
   jsonb_build_object('sector_key','iron','industry','industrial')),

  (v_type_id, NULL, 'stainless-steel', 'الستانلس ستيل', 'Stainless Steel',
   'درابزين، مطابخ، تجاليد، أعمال فنية ومعدات استانلس.',
   'Handrails, kitchens, claddings, decorative and equipment stainless steel.',
   'يشمل أعمال الستانلس ستيل المعمارية والصناعية: الدرابزينات، المطابخ التجارية والمنزلية، التجاليد، أنابيب الحماية، الأدوات الفنية والإكسسوارات.',
   'Covers architectural and industrial stainless steel: handrails, commercial and home kitchens, claddings, guard rails, decorative works and accessories.',
   'قطاع الستانلس ستيل', 'Stainless Steel Sector',
   'كل أعمال الستانلس ستيل: درابزين، مطابخ، تجاليد، أعمال فنية وإكسسوارات.',
   'All stainless steel work: handrails, kitchens, claddings, decorative pieces and accessories.',
   ARRAY['ستانلس ستيل','درابزين ستانلس','مطابخ ستانلس','تجاليد','إكسسوارات ستانلس'],
   ARRAY['stainless steel','stainless handrails','stainless kitchens','claddings','decorative steel'],
   'Factory', '#94A3B8', 40,
   true,true,true,true,false, true,true,true,true,true,true,true,false,
   jsonb_build_object('sector_key','stainless_steel','industry','industrial')),

  (v_type_id, NULL, 'wood-sector', 'الخشب والأبواب الخشبية', 'Wood & Wood Doors',
   'أبواب خشبية، ديكورات، أرضيات، وفرش داخلي خشبي.',
   'Wood doors, decoratives, flooring and interior wood works.',
   'يشمل قطاع الخشب أعمال النجارة المعمارية: الأبواب الخشبية بأنواعها (مصمت، حشو، CNC، قشرة)، الباركيه والأرضيات، الديكورات الخشبية، الأثاث الثابت، والفرش الداخلي.',
   'Covers architectural carpentry: wooden doors (solid, infill, CNC, veneer), parquet and flooring, decorative panels, built-in furniture and fit-outs.',
   'قطاع الخشب والأبواب الخشبية', 'Wood & Wood Doors Sector',
   'متخصصو الأبواب الخشبية والديكورات والأرضيات الخشبية وأعمال النجارة المعمارية.',
   'Specialists in wood doors, wooden decoratives, parquet and architectural carpentry.',
   ARRAY['خشب','أبواب خشب','نجارة','باركيه','ديكور خشبي','قشرة خشب','CNC خشب'],
   ARRAY['wood','wood doors','carpentry','parquet','wood decor','veneer','CNC wood'],
   'TreePine', '#16A34A', 50,
   true,true,true,true,false, true,true,true,true,true,true,true,false,
   jsonb_build_object('sector_key','wood','industry','industrial')),

  (v_type_id, NULL, 'kitchens', 'المطابخ', 'Kitchens',
   'مطابخ بكل خاماتها: خشب، ألمنيوم، ستانلس، بولي لاك.',
   'Kitchens in every material: wood, aluminum, stainless steel, poly-lac.',
   'يجمع قطاع المطابخ تصاميم وتنفيذ المطابخ المنزلية والتجارية بكافة الخامات: المطابخ الخشبية بالـ HPL والقشرة، مطابخ الألمنيوم بالحُقن، المطابخ الستانلس ستيل، ومطابخ البولي لاك العالية اللمعان.',
   'Brings together design and execution of residential and commercial kitchens across all materials: wood (HPL, veneer), injected aluminum, stainless steel and high-gloss poly-lac kitchens.',
   'قطاع المطابخ', 'Kitchens Sector',
   'مصممو ومصنّعو المطابخ بكل أنواع الخامات والأجهزة الحديثة.',
   'Kitchen designers and manufacturers covering every material and modern appliance set.',
   ARRAY['مطابخ','مطبخ خشب','مطبخ ألمنيوم','مطبخ ستانلس','بولي لاك','مطابخ تجارية','تصميم مطابخ'],
   ARRAY['kitchens','wood kitchen','aluminum kitchen','stainless kitchen','poly-lac','commercial kitchens','kitchen design'],
   'Grid3X3', '#F97316', 60,
   true,true,true,true,false, true,true,true,true,true,true,true,false,
   jsonb_build_object('industry','industrial','is_parent_sector',true)),

  (v_type_id, NULL, 'upvc', 'UPVC أبواب وشبابيك', 'UPVC Doors & Windows',
   'الـ UPVC للأبواب والشبابيك بالعزل الحراري والصوتي.',
   'UPVC doors and windows with thermal and acoustic insulation.',
   'يضم قطاع الـ UPVC تصنيع وتركيب الأبواب والشبابيك من بروفايلات الـ UPVC ذات الكفاءة الحرارية العالية ومقاومة الأشعة فوق البنفسجية، مع اعتمادات أوروبية وإكسسوارات ألمانية وزجاج معزول.',
   'Covers fabrication and installation of UPVC doors and windows using high thermal-efficiency UV-resistant profiles with European certifications, German hardware and insulated glazing.',
   'قطاع UPVC', 'UPVC Sector',
   'متخصصو أبواب وشبابيك UPVC مع العزل الحراري والصوتي وأفضل البروفايلات.',
   'UPVC door and window specialists with thermal/acoustic insulation and top profile brands.',
   ARRAY['UPVC','أبواب UPVC','شبابيك UPVC','عزل حراري','عزل صوتي','بروفايل ألماني'],
   ARRAY['UPVC','UPVC doors','UPVC windows','thermal insulation','acoustic insulation','german profile'],
   'Wrench', '#22C55E', 70,
   true,true,true,true,false, true,true,true,true,true,true,true,false,
   jsonb_build_object('industry','industrial')),

  (v_type_id, NULL, 'facades', 'الواجهات', 'Facades',
   'كلادينج، GRC، زجاج هيكلي، حجر وكسوات معمارية.',
   'Cladding, GRC, structural glazing, stone and architectural skins.',
   'يشمل قطاع الواجهات تصميم وتنفيذ الكسوات المعمارية: كلادينج الألمنيوم والـ ACP، الـ GRC والـ GRP، الواجهات الزجاجية الهيكلية والـ Spider، كسوات الحجر الطبيعي والصناعي.',
   'Covers design and execution of architectural skins: aluminum and ACP cladding, GRC and GRP panels, structural and spider glazing, natural and engineered stone.',
   'قطاع الواجهات المعمارية', 'Architectural Facades Sector',
   'متخصصو الكلادينج والواجهات الزجاجية والحجرية والـ GRC.',
   'Specialists in cladding, glass façades, stone façades and GRC systems.',
   ARRAY['واجهات','كلادينج','ACP','GRC','واجهات زجاجية','واجهات حجر'],
   ARRAY['facades','cladding','ACP','GRC','glass facades','stone facades'],
   'Home', '#0EA5E9', 80,
   true,true,true,true,false, true,true,true,true,true,true,true,false,
   jsonb_build_object('industry','industrial')),

  (v_type_id, NULL, 'fire-doors', 'أبواب مقاومة للحريق', 'Fire-Rated Doors',
   'أبواب وقواطع مقاومة للحريق بفترات حماية معتمدة.',
   'Fire-rated doors and partitions with certified protection ratings.',
   'يضم قطاع أبواب الحريق توريد وتركيب الأبواب والقواطع والـ Shutters المقاومة للحريق بفترات حماية معتمدة (60، 90، 120، 180 دقيقة) مع شهادات BS و UL ومتطلبات الدفاع المدني.',
   'Covers supply and installation of fire-rated doors, partitions and shutters with certified protection durations (60, 90, 120, 180 min), BS/UL certifications and civil defense compliance.',
   'قطاع أبواب مقاومة الحريق', 'Fire-Rated Doors Sector',
   'متخصصو أبواب الحريق المعتمدة من الدفاع المدني وفق معايير BS و UL.',
   'Civil-defense certified fire door specialists complying with BS and UL standards.',
   ARRAY['أبواب حريق','مقاومة الحريق','الدفاع المدني','BS','UL','قواطع حريق'],
   ARRAY['fire doors','fire-rated','civil defense','BS','UL','fire partitions'],
   'Flame', '#DC2626', 90,
   true,true,true,true,false, true,true,true,true,true,true,true,false,
   jsonb_build_object('industry','industrial')),

  (v_type_id, NULL, 'gates-structures', 'البوابات والمظلات والهناجر', 'Gates, Pergolas & Hangars',
   'البوابات الكهربائية، المظلات، السواتر، الهناجر الصناعية.',
   'Electric gates, pergolas, screens, industrial hangars.',
   'يضم القطاع تصنيع وتركيب البوابات الكهربائية بأنواعها (انزلاقية، مفصلية، تلسكوبية)، المظلات والبرجولات، السواتر، الهناجر الصناعية والزراعية والـ Steel Buildings الجاهزة.',
   'Includes fabrication and installation of electric gates (sliding, swing, telescopic), pergolas and canopies, privacy screens, industrial and agricultural hangars and pre-engineered steel buildings.',
   'قطاع البوابات والمظلات والهناجر', 'Gates, Pergolas & Hangars Sector',
   'متخصصو البوابات الكهربائية والمظلات والهناجر والمباني المعدنية.',
   'Electric gate, pergola, hangar and pre-engineered steel building specialists.',
   ARRAY['بوابات كهربائية','مظلات','برجولات','هناجر','سواتر','مباني معدنية'],
   ARRAY['electric gates','pergolas','hangars','canopies','privacy screens','steel buildings'],
   'DoorOpen', '#EA580C', 100,
   true,true,true,true,false, true,true,true,true,true,true,true,false,
   jsonb_build_object('industry','industrial')),

  (v_type_id, NULL, 'wardrobes-closets', 'خزائن ودواليب', 'Wardrobes & Closets',
   'خزائن داخلية، Walk-in Closet، دواليب ملابس بكل الخامات.',
   'Built-in wardrobes, walk-in closets and clothing storage in every material.',
   'يشمل قطاع الخزائن والدواليب تصميم وتنفيذ الخزائن الداخلية الـ Built-in وخزائن الـ Walk-in Closet ودواليب الملابس بكل الخامات: الخشب، الألمنيوم، MDF، والـ HPL — مع إكسسوارات Hettich و Hafele.',
   'Includes design and execution of built-in wardrobes, walk-in closets and clothing storage in all materials: wood, aluminum, MDF, HPL — with Hettich and Hafele hardware.',
   'قطاع الخزائن والدواليب', 'Wardrobes & Closets Sector',
   'متخصصو الخزائن الداخلية والـ Walk-in Closet ودواليب الملابس بكل الخامات.',
   'Specialists in built-in wardrobes, walk-in closets and clothing storage in every material.',
   ARRAY['خزائن','دواليب','Walk-in closet','خزائن داخلية','MDF','HPL','Hettich','Hafele'],
   ARRAY['wardrobes','closets','walk-in closet','built-in wardrobes','MDF','HPL','Hettich','Hafele'],
   'Layers', '#A855F7', 110,
   true,true,true,true,false, true,true,true,true,true,true,true,false,
   jsonb_build_object('industry','industrial'))
  ON CONFLICT (slug) DO UPDATE SET
    name_ar = EXCLUDED.name_ar, name_en = EXCLUDED.name_en,
    short_description_ar = EXCLUDED.short_description_ar, short_description_en = EXCLUDED.short_description_en,
    description_ar = EXCLUDED.description_ar, description_en = EXCLUDED.description_en,
    seo_title_ar = EXCLUDED.seo_title_ar, seo_title_en = EXCLUDED.seo_title_en,
    seo_description_ar = EXCLUDED.seo_description_ar, seo_description_en = EXCLUDED.seo_description_en,
    keywords_ar = EXCLUDED.keywords_ar, keywords_en = EXCLUDED.keywords_en,
    icon = EXCLUDED.icon, color = EXCLUDED.color, sort_order = EXCLUDED.sort_order,
    metadata = public.taxonomy_categories.metadata || EXCLUDED.metadata,
    updated_at = now();

  -- Kitchen sub-types
  SELECT id INTO v_kitchens_id
  FROM public.taxonomy_categories
  WHERE taxonomy_type_id = v_type_id AND slug = 'kitchens' LIMIT 1;

  IF v_kitchens_id IS NOT NULL THEN
    INSERT INTO public.taxonomy_categories (
      taxonomy_type_id, parent_id, slug, name_ar, name_en,
      short_description_ar, short_description_en,
      keywords_ar, keywords_en, icon, color, sort_order,
      is_active, is_public, is_searchable,
      show_in_registration, show_in_search, show_in_seo, show_in_showcase,
      show_in_products, show_in_contracts, show_in_quotes, show_in_admin_only,
      metadata
    ) VALUES
    (v_type_id, v_kitchens_id, 'kitchens-wood', 'مطابخ خشبية', 'Wood Kitchens',
     'مطابخ خشب HPL والقشرة الطبيعية والمصبوغة.',
     'HPL, natural veneer and painted wood kitchens.',
     ARRAY['مطبخ خشب','HPL','قشرة','MDF خشب'], ARRAY['wood kitchen','HPL','veneer','MDF wood'],
     'TreePine', '#15803D', 10,
     true,true,true, true,true,true,true,true,true,true,false,
     jsonb_build_object('parent_sector_slug','kitchens','material','wood')),
    (v_type_id, v_kitchens_id, 'kitchens-aluminum', 'مطابخ ألمنيوم', 'Aluminum Kitchens',
     'مطابخ ألمنيوم بالحُقن مقاومة للماء والحرارة.',
     'Injected aluminum kitchens, water and heat resistant.',
     ARRAY['مطبخ ألمنيوم','حقن ألمنيوم','مقاوم ماء'], ARRAY['aluminum kitchen','injected aluminum','water resistant'],
     'PanelTop', '#2563EB', 20,
     true,true,true, true,true,true,true,true,true,true,false,
     jsonb_build_object('parent_sector_slug','kitchens','material','aluminum')),
    (v_type_id, v_kitchens_id, 'kitchens-stainless', 'مطابخ ستانلس ستيل', 'Stainless Steel Kitchens',
     'مطابخ تجارية ومنزلية من الستانلس ستيل 304 و 316.',
     'Commercial and home stainless steel kitchens (304 / 316).',
     ARRAY['مطبخ ستانلس','مطابخ مطاعم','ستانلس 304','ستانلس 316'], ARRAY['stainless kitchen','restaurant kitchens','SS 304','SS 316'],
     'Factory', '#64748B', 30,
     true,true,true, true,true,true,true,true,true,true,false,
     jsonb_build_object('parent_sector_slug','kitchens','material','stainless_steel')),
    (v_type_id, v_kitchens_id, 'kitchens-polylac', 'مطابخ بولي لاك', 'Poly-Lac Kitchens',
     'مطابخ بولي لاك عالية اللمعان بألوان متعددة.',
     'High-gloss poly-lac kitchens in multiple colors.',
     ARRAY['بولي لاك','مطابخ لامعة','high gloss'], ARRAY['poly-lac','glossy kitchens','high gloss'],
     'Grid3X3', '#DB2777', 40,
     true,true,true, true,true,true,true,true,true,true,false,
     jsonb_build_object('parent_sector_slug','kitchens','material','polylac'))
    ON CONFLICT (slug) DO UPDATE SET
      name_ar = EXCLUDED.name_ar, name_en = EXCLUDED.name_en,
      short_description_ar = EXCLUDED.short_description_ar, short_description_en = EXCLUDED.short_description_en,
      keywords_ar = EXCLUDED.keywords_ar, keywords_en = EXCLUDED.keywords_en,
      icon = EXCLUDED.icon, color = EXCLUDED.color, sort_order = EXCLUDED.sort_order,
      parent_id = EXCLUDED.parent_id,
      metadata = public.taxonomy_categories.metadata || EXCLUDED.metadata,
      updated_at = now();
  END IF;
END $$;
