-- Phase 2.3 — Generalize image pipeline to services + products.

-- business_services: no image columns yet. Add legacy url + asset link + variants map.
ALTER TABLE public.business_services
  ADD COLUMN IF NOT EXISTS image_url TEXT,
  ADD COLUMN IF NOT EXISTS image_asset_id UUID REFERENCES public.image_assets(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS image_variants JSONB NOT NULL DEFAULT '{}'::jsonb;

CREATE INDEX IF NOT EXISTS idx_business_services_image_asset_id
  ON public.business_services(image_asset_id)
  WHERE image_asset_id IS NOT NULL;

-- brand_products already has image_url + gallery; add asset linkage.
ALTER TABLE public.brand_products
  ADD COLUMN IF NOT EXISTS image_asset_id UUID REFERENCES public.image_assets(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS image_variants JSONB NOT NULL DEFAULT '{}'::jsonb;

CREATE INDEX IF NOT EXISTS idx_brand_products_image_asset_id
  ON public.brand_products(image_asset_id)
  WHERE image_asset_id IS NOT NULL;

COMMENT ON COLUMN public.business_services.image_variants IS
  'Phase 2.3: responsive WebP variant URLs (thumbnail/card/medium/hero) generated by image-pipeline.';
COMMENT ON COLUMN public.brand_products.image_variants IS
  'Phase 2.3: responsive WebP variant URLs (thumbnail/card/medium/hero) generated by image-pipeline.';
